development:
  session_secret: 'abc123'
  facebook_id: <%= ENV['NOODLE_FB_ID'] %>
  facebook_secret: <%= ENV['NOODLE_FB_SECRET'] %>
  github_id: <%= ENV['NOODLE_GITHUB_ID'] %>
  github_secret: <%= ENV['NOODLE_GITHUB_SECRET'] %>

test:

staging:

production: